/** TaskPoolLogicV2 最小 ABI（竖切 / 读状态） */
export const taskPoolAbi = [
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pointToken',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'remarkProxy',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'credit',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'creditNonces',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createTaskPool',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'publisher', type: 'address' },
      { name: 'taskIds', type: 'uint256[]' },
      { name: 'taskMaxAmounts', type: 'uint256[]' },
      { name: 'lockedBalance', type: 'uint256' },
      { name: 'claimDeadline', type: 'uint256' },
      { name: 'credentialDeadline', type: 'uint256' },
      { name: 'nonce', type: 'uint256' },
      { name: 'sigDeadline', type: 'uint256' },
      { name: 'signature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimTask',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'taskId', type: 'uint256' },
      { name: 'amount', type: 'uint256' },
      { name: 'sigDeadline', type: 'uint256' },
      { name: 'signature', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'approveSubtask',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'taskId', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'finalApprovePool',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'publisherRemark', type: 'string' },
      { name: 'remarkTaskIds', type: 'uint256[]' },
      { name: 'assigneeRemarks', type: 'string[]' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'distribute',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'poolId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pools',
    stateMutability: 'view',
    inputs: [{ name: 'poolId', type: 'uint256' }],
    outputs: [
      { name: 'publisher', type: 'address' },
      { name: 'manager', type: 'address' },
      { name: 'lockedBalance', type: 'uint256' },
      { name: 'allocated', type: 'uint256' },
      { name: 'claimDeadline', type: 'uint256' },
      { name: 'publicizeEligibleAt', type: 'uint64' },
      { name: 'publicizeEndsAt', type: 'uint64' },
      { name: 'paused', type: 'bool' },
      { name: 'settled', type: 'bool' },
      { name: 'taskIds', type: 'uint256[]' },
      { name: 'exists', type: 'bool' },
      { name: 'credentialDeadline', type: 'uint256' },
      { name: 'poolRejected', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'poolTasks',
    stateMutability: 'view',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'taskId', type: 'uint256' },
    ],
    outputs: [
      { name: 'assignee', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'maxAmount', type: 'uint256' },
      { name: 'claimNonce', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'exists', type: 'bool' },
    ],
  },
] as const

export const erc20Abi = [
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
] as const
